### NumPy is pure gold. It is fast, easy to learn, feature-rich, and therefore at the core of almost all popular scientific packages in the Python universe (including SciPy and Pandas, which are two most widely used packages for data science and statistical modeling).

In [2]:
#Import Numpy library:
import numpy as np

In [3]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> quit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [6]:
#Checking version of installed Numpy:
np.__version__

'1.18.3'

In [7]:
speed = []  #Define a new list for storing speed after each calculation.
speed = distances / times
print(speed)

NameError: name 'distances' is not defined

In [ ]:
# LISTs are good, you can change values but you cannot apply mathematical functions on it.
distances = [10, 15, 17, 26]
times     = [1,   2,  3,  4]

In [ ]:
for distance in distances:
    for time in times:   
        speed = distance/time
        print(speed)
    print('---------')

In [ ]:
import numpy as np

In [ ]:
test_arr = array([10, 15, 17, 26],dtype=np.int64)
test_arr

In [ ]:
test_arr.dtype

In [ ]:
np_distance = np.array(distances)
np_time     = np.array(times)

In [ ]:
np_distance

In [ ]:
np_time

In [ ]:
np_speed = np_distance / np_time
np_speed

In [ ]:
[10,20,30,40] * 2

In [ ]:
np_distance

In [ ]:
np_distance * 2

In [ ]:
distance

In [ ]:
time

In [ ]:
speed = distances / times

#### Creating numpy array:

In [ ]:
np_distance

In [ ]:
np_distance.ndim

In [ ]:
np_distance.shape

In [ ]:
np_distance.size

In [ ]:
# why use numpy
# compare numpy array with standard python LIST type array

In [ ]:
for num in range(0,10,2):
    print(num)

In [ ]:
#List Size:
distance

In [ ]:
sys.getsizeof(time)

In [ ]:
np_distance

In [ ]:
sys.getsizeof(time)

In [ ]:
sys.getsizeof("TEFJEBFjkrb")

In [ ]:
2**16

In [ ]:
np.int

In [ ]:
sys.getsizeof(60000)

In [ ]:
# Example - getsizeof
print('Integer memory size : ', sys.getsizeof(5) )
print('Integer memory size : ', sys.getsizeof(56666666) )
print('Integer memory size : ', sys.getsizeof(56666669559956) )
print('Float   memory size : ', sys.getsizeof(5.05) )
print('Float   memory size : ', sys.getsizeof(5.058585885) )

print('\nString  memory size : ',sys.getsizeof('1') )
print('String  memory size : ',sys.getsizeof('A') )
print('String  memory size : ',sys.getsizeof('AA') )
print('String  memory size : ',sys.getsizeof('AAA') )
print('String  memory size : ',sys.getsizeof('AAAA') )
print('String  memory size : ',sys.getsizeof('AAAAA') )

In [ ]:
print(np_arr2)

In [ ]:
# NumPy-based algorithms are generally 10 to 100 times faster (or more) 
# than their pure Python counterparts and use significantly less memory.

In [ ]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

In [ ]:
arr_shape = array_2d.shape
arr_shape

In [ ]:
array_2d.ndim

In [ ]:
array_2d.size

In [ ]:
test.ndim

In [ ]:
test.shape

In [ ]:
test.size

#### np.linspace( ):

In [ ]:
# linespace
# Equally-spaced numbers

In [ ]:
test_arr = np.linspace(1,10,num=20)
test_arr

In [ ]:
1.94736842 - 1.47368421

In [ ]:
2.42105263 - 1.94736842

In [ ]:
2.89473684 - 2.42105263

In [ ]:
test_arr.shape

In [ ]:
test_arr.ndim

In [ ]:
test = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(test)

In [ ]:
np.linspace(0, 5, 10)

### RANDOM:

### 1st Function::

In [ ]:
# The random module provides functions to generate random numbers 
# (and also statistical distributions) of any given shape.

# numpy.random.randn generates samples from the normal distribution, 
# numpy.random.rand  generates samples from the unifrom (in range [0,1)).
np.random.rand(5)

In [ ]:
# Random numbers between [0,1) of shape 2,3
result_arry = np.random.rand(2, 3)
result_arry

In [ ]:
result_arry = np.random.rand(2, 3, 3)
result_arry

In [ ]:
result_arry.ndim

### 2nd Function::

In [ ]:
np.random.randint()

In [ ]:
np.random.randint(10,25,size=15)

In [ ]:
# Random integers between [5, 10) of shape 5,5:
print(np.random.randint(5, 10, size=(5,5)))

In [22]:
result_arr = np.random.randint(5,10,size=(5,5))

In [23]:
type(result_arr)

numpy.ndarray

In [24]:
result_arr.

array([[6, 6, 8, 6, 8],
       [7, 6, 9, 9, 9],
       [8, 7, 7, 6, 9],
       [7, 6, 9, 5, 5],
       [8, 8, 6, 7, 6]])

In [ ]:
result_arr.ndim

In [ ]:
# Pick 3 items from a given list, with equal probability
print(np.random.choice(['deepak', 'raj', 'rakesh', 'owl', 'monkey'], size=3))  

## -----------STARTING--------------

### If you want to repeat the same set of random numbers every time, you need to set the seed  or the random state. The seed can be any value. The only requirement is you must set the seed  to the same value every time you want to generate the same set of random numbers.

- Once np.random.RandomState is created, all the functions of the np.random module becomes available to the created randomstate object.

In [8]:
np.random.RandomState()

RandomState(MT19937) at 0x1D17AAE3268

In [46]:
# Create the random state
rn = np.random.RandomState(234)
rn.randint(5,50,size=(5,5))

array([[13, 36,  9, 36, 38],
       [ 8, 44,  8, 39, 13],
       [31, 33, 24, 44, 26],
       [12, 41, 37,  5, 31],
       [12, 42, 28,  8, 20]])

In [50]:
rn = np.random.RandomState(4)
print(rn.randint(5,50,(5,5)))

[[10  6 45 28 13]
 [14 44 35 45 41]
 [49 43 47  8  5]
 [26 26 14 43 43]
 [ 7 35 13  7 28]]


In [60]:
r_s = np.random.RandomState(43)
print(r_s.randint(5,50,(5,5)))

[[ 9  5 26 21 22]
 [32  7 35 28  5]
 [40 16 30  6 39]
 [16  7 40  9 41]
 [17 29 37 15 14]]


In [66]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0 1 2 3 4 5 6 7 9]
Counts       :  [3 3 5 2 2 4 2 3 1]


In [67]:
data

array([[-1.79221791, -0.03995975, -0.63488723],
       [ 0.24388602, -0.98601283, -0.9810088 ],
       [-1.2326257 ,  0.58095375,  0.34117983]])

In [65]:
# How to get the unique items and the counts?
# The np.unique method can be used to get the unique items. 
# If you want the repetition counts of each item, set the return_counts parameter to True.

# Create random integers of size 10 between [0,10)
np.random.seed(1090)
arr_rand = np.random.randint(0, 10, size=(5,5))
print(arr_rand)

[[6 3 2 2 6]
 [7 4 0 2 7]
 [4 0 5 2 5]
 [1 7 3 1 5]
 [9 5 1 2 0]]


In [68]:
#Scalar Multiplication:
arr_rand * 10

array([[60, 30, 20, 20, 60],
       [70, 40,  0, 20, 70],
       [40,  0, 50, 20, 50],
       [10, 70, 30, 10, 50],
       [90, 50, 10, 20,  0]])

In [75]:
#Scalar division:
arr_rand / 10

array([[0.6, 0.3, 0.2, 0.2, 0.6],
       [0.7, 0.4, 0. , 0.2, 0.7],
       [0.4, 0. , 0.5, 0.2, 0.5],
       [0.1, 0.7, 0.3, 0.1, 0.5],
       [0.9, 0.5, 0.1, 0.2, 0. ]])

In [70]:
#Scalar Addition:
arr_rand + 10

array([[16, 13, 12, 12, 16],
       [17, 14, 10, 12, 17],
       [14, 10, 15, 12, 15],
       [11, 17, 13, 11, 15],
       [19, 15, 11, 12, 10]])

In [71]:
#Scalar Sub:
arr_rand - 10

array([[ -4,  -7,  -8,  -8,  -4],
       [ -3,  -6, -10,  -8,  -3],
       [ -6, -10,  -5,  -8,  -5],
       [ -9,  -3,  -7,  -9,  -5],
       [ -1,  -5,  -9,  -8, -10]])

### Array of Zero:

In [76]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
b = np.zeros((4, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
c = np.zeros_like(b)
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Array of ones:

In [81]:
# ones
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
b = np.ones((3, 6))
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [83]:
c = np.ones_like(b)
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### Function -- arange( ) [IMPORTANT]

In [84]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
c = np.arange(5,50,5).reshape(3,3)
c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [88]:
c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Conditional setting:

In [91]:
c > 15

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

### Condional element fetching:

In [92]:
c[c > 15].reshape(3,2)

array([[20, 25],
       [30, 35],
       [40, 45]])

In [ ]:
# Basic Indexing and Slicing
arr = np.arange(10)
arr

In [ ]:
arr[5]

In [ ]:
arr[5:8]

In [ ]:
# broadcasting a value to multiple array positions
arr[5: 8] = 12

In [ ]:
arr

In [ ]:
arr_slice = arr[5: 8]
arr_slice

In [ ]:
# change values in arr_slice, the mutations are reflected in the original 
# array arr
arr_slice[0] = 12345

In [ ]:
arr_slice

In [ ]:
arr

In [ ]:
# using : only means all values
arr_slice[1:2] = 9999

In [ ]:
arr_slice

In [ ]:
arr

In [ ]:
# if you just assign a portion of an array to another array, the new array you just 
# created actually refers to the parent array in memory.
# That means, if you make any changes to the new array, it will reflect in the parent 
# array as well.

# So to avoid disturbing the parent array, you need to make a copy of it using copy(). 
# All numpy arrays come with the copy() method.

In [ ]:
# If you want a copy of a slice of an ndarray instead of a view, you
# will need to explicitly copy the array — for example,
# arr[5:8].copy().
arr_slice = arr[5:8].copy()

In [ ]:
arr_slice

In [ ]:
arr_slice[:] = 888

In [ ]:
arr_slice

In [ ]:
# the original array is not changed
arr

In [ ]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]

arr2 = np.array(list2, dtype='float')
arr2

In [ ]:
arr2a = arr2[:2,:2]  
arr2a[:1, :1] = 100  # 100 will reflect in arr2
arr2

In [ ]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 101  # 101 will not reflect in arr2
arr2

In [ ]:
# Indexing with slices
arr = np.arange(10)

In [ ]:
arr

In [ ]:
arr[1:6]

In [109]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr2d

In [ ]:
arr2d[2]

In [ ]:
arr2d[0][2]

In [ ]:
# expression arr2d[:2] as “select the first two rows of arr2d.”
arr2d[:2]

In [110]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
# first 2 rows and all columns from 1st pos
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [112]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [113]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
# 1st row, all columns 0th and 1st
arr2d[1, :2]

array([4, 5])

In [118]:
arr2d[:2, 2]

array([3, 6])

In [120]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
arr2d[:, 1]

array([2, 5, 8])

In [93]:
c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
c[c % 2 == 0] = 0

In [97]:
c

array([[ 5,  0, 15],
       [ 0, 25,  0],
       [35,  0, 45]])

In [122]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [86]:
names.dtype

dtype('<U7')

In [31]:
data

array([[ 1.22929353,  0.29854477,  1.99621675,  0.26785254],
       [-2.08050317,  1.77854433,  1.22005339, -0.47781745],
       [ 0.33765768, -1.39167446, -0.17194337,  0.5237974 ],
       [ 0.69479263, -1.41532591,  2.77600422,  0.62222235],
       [ 0.30793354,  0.19525426, -1.01553749,  0.80056237],
       [ 1.15743546,  0.40392278, -0.84709449,  0.11524676],
       [-0.44425798, -0.32641626,  0.18107691, -0.13992714]])

In [30]:
# Boolean Indexing
names = np.array(['Rajat', 'Maruthi', 'Dinesh', 'Rajat', 'Bhanu', 'Viswa', 'Kamal'])
data  = np.random.randn(7, 4)

In [32]:
# Suppose each name corresponds to a row in the data array and we wanted to 
# select all the rows with corresponding name 'Rajat'.
names == 'Rajat'

array([ True, False, False,  True, False, False, False])

In [90]:
data[names == 'Rajat']

array([[ 0.74934468, -1.93176098, -0.9982326 , -0.25454555],
       [ 0.70471712,  1.77753088, -0.67452911,  0.29169769]])

In [40]:
# The boolean array must be of the same length as the array axis it’s 
# indexing.

In [33]:
# what happens if they are of different lengths
names = np.array(['Rajat', 'Maruthi', 'Rajat', 'Bhanu', 'Viswa' ])
data = np.random.randn(7, 4)

In [34]:
data[names == 'Rajat']

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5

In [36]:
names = np.array(['Rajat', 'Maruthi', 'Dinesh', 'Rajat', 'Bhanu', 'Viswa', 'Kamal'])
data = np.random.randn(7, 4)
data

array([[ 0.08307716, -0.34051008,  0.05570882, -1.04279505],
       [-0.42919629, -1.17734804, -1.02140811, -0.01448326],
       [-1.38800379,  0.77476985,  1.78426911,  1.28029017],
       [-0.28547048,  0.19907383,  0.54815728, -0.99088815],
       [ 0.75547603, -1.23810542,  0.11721089, -1.69294012],
       [-0.59595512,  2.18457115, -0.89288659, -0.63624133],
       [ 1.35834876, -0.41627882, -1.17159329, -0.68006964]])

In [37]:
data[names == 'Rajat', :2]

array([[ 0.08307716, -0.34051008],
       [-0.28547048,  0.19907383]])

In [38]:
data[names == 'Rajat', 2]

array([0.05570882, 0.54815728])

In [133]:
# To select everything but 'Rajat', you can either use != or negate 
# the condition using ~

In [39]:
names != 'Rajat'

array([False,  True,  True, False,  True,  True,  True])

In [40]:
data[names != 'Rajat']

array([[-0.42919629, -1.17734804, -1.02140811, -0.01448326],
       [-1.38800379,  0.77476985,  1.78426911,  1.28029017],
       [ 0.75547603, -1.23810542,  0.11721089, -1.69294012],
       [-0.59595512,  2.18457115, -0.89288659, -0.63624133],
       [ 1.35834876, -0.41627882, -1.17159329, -0.68006964]])

In [41]:
data[~(names == 'Rajat')]

array([[-0.42919629, -1.17734804, -1.02140811, -0.01448326],
       [-1.38800379,  0.77476985,  1.78426911,  1.28029017],
       [ 0.75547603, -1.23810542,  0.11721089, -1.69294012],
       [-0.59595512,  2.18457115, -0.89288659, -0.63624133],
       [ 1.35834876, -0.41627882, -1.17159329, -0.68006964]])

In [97]:
cond = names == 'Rajat'

In [98]:
data[cond]

array([[-0.53167093,  1.05635313, -0.58443075, -0.60523825],
       [ 1.06811309, -1.08530938,  0.8847015 , -0.33150969]])

In [99]:
data[~cond]

array([[ 0.05875981, -0.68681785,  1.34471203,  0.33285342],
       [-1.27283038, -0.27812818, -0.07161781,  0.5596244 ],
       [-1.58197846, -1.97266763,  0.56501394,  0.54106927],
       [-0.2480986 ,  0.9176196 , -0.89054672,  1.12037934],
       [ 0.28394138,  0.67916219, -1.1503419 ,  0.08673909]])

In [140]:
# Selecting two of the three names to combine multiple boolean conditions, 
# use boolean arithmetic operators like & (and) and | (or):

In [100]:
# The Python keywords and and or do not work with boolean arrays.
# Use & (and) and | (or) instead.
cond = (names == 'Rajat') | (names == 'Bhanu')

In [101]:
data[cond]

array([[-0.53167093,  1.05635313, -0.58443075, -0.60523825],
       [ 1.06811309, -1.08530938,  0.8847015 , -0.33150969],
       [-1.58197846, -1.97266763,  0.56501394,  0.54106927]])

In [143]:
cond = data > 0

In [144]:
data[cond]

array([ 1.56464366,  0.8219025 ,  0.08704707,  0.09176078,  0.35711257,
        1.47789404,  0.91540212,  0.32875111,  0.51326743,  0.09707755,
        0.96864499,  0.29612028,  0.26105527,  0.00511346])

In [145]:
data[cond] = 0

In [146]:
data

array([[ 0.        , -2.6197451 ,  0.        ,  0.        ],
       [-0.29900735,  0.        , -1.98756891, -0.21967189],
       [ 0.        ,  0.        , -0.51827022, -0.8084936 ],
       [-0.50175704,  0.        ,  0.        , -0.5297602 ],
       [ 0.        ,  0.        ,  0.        , -0.70205309],
       [-0.32766215, -0.39210815, -1.46351495,  0.        ],
       [ 0.        ,  0.        , -0.23458713, -1.41537074]])

In [102]:
# change data for Rajat = 7
data[names != 'Rajat'] = 7

In [103]:
data

array([[-0.53167093,  1.05635313, -0.58443075, -0.60523825],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.06811309, -1.08530938,  0.8847015 , -0.33150969],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ]])

In [149]:
# Transposing Arrays and Swapping Axes
# Transposing is a special form of reshaping that similarly returns a view on the underlying
# data without copying anything

In [98]:
a = np.array([(8,9,10),(11,12,13)])
print(a)

[[ 8  9 10]
 [11 12 13]]


In [99]:
a=a.reshape(6,1)
print(a)

[[ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [100]:
a.ndim

2

In [101]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [104]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Square-root:

In [108]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### Exponential:

In [156]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [121]:
arr = np.arange(10,dtype=np.float32)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [126]:
arr[4:7] = np.nan

In [127]:
arr

array([ 0.,  1.,  2.,  3., nan, nan, nan,  7.,  8.,  9.], dtype=float32)

In [134]:
test = arr[4]
test

nan

In [135]:
type(test)

numpy.float32

In [138]:
2**32

4294967296

In [137]:
help(float)

Help on class float in module builtins:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(sel

In [130]:
# useful in data anlytics
# is not a number
np.isnan(arr).sum()

3

### Element by Element comparision:

In [112]:
# binary functions
x = np.random.randint(0,10,8)
x

array([1, 7, 0, 9, 1, 9, 5, 2])

In [113]:
y = np.random.randint(0,10,8)
y

array([1, 2, 5, 2, 3, 8, 6, 1])

In [114]:
np.maximum(x, y)

array([1, 7, 5, 9, 3, 9, 6, 2])

In [116]:
np.minimum(x, y)

array([1, 2, 0, 2, 1, 8, 5, 1])

In [ ]:
# Array-Oriented Programming with Arrays
# NumPy arrays enables you to express many kinds of data processing tasks 
# as concise array expressions that might otherwise require writing loops

In [ ]:
# This practice of replacing explicit loops with array expressions 
# is commonly referred to as vectorization.

In [ ]:
# vectorized array operations will often be one or two (or more) orders
# of magnitude faster than their pure Python equivalents

In [26]:
# to evaluate the function sqrt(x^2 + y^2) 
# across a regular grid of values.

In [162]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points

In [163]:
x = np.arange(10)
y = np.arange(10)

In [164]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
np.sqrt(np.add(x ** 2 , y ** 2))

array([  0.        ,   1.41421356,   2.82842712,   4.24264069,
         5.65685425,   7.07106781,   8.48528137,   9.89949494,
        11.3137085 ,  12.72792206])

In [ ]:
# random number **********************************************

In [253]:
# mean at 0 and standard deviation of 1
# This will return random floats in the half-open interval [0.0, 1.0) 
# following the “continuous uniform” distribution.
np.random.randn(5)

array([ 0.09176078, -1.98756891, -0.21967189,  0.35711257,  1.47789404])

In [254]:
np.random.random((2,2))

array([[ 0.22879817,  0.07697991],
       [ 0.28975145,  0.16122129]])

In [255]:
# Generate A Random Number From The Normal Distribution
np.random.normal()

-0.5182702182736474

In [256]:
# Generate Four Random Numbers From The Normal Distribution
np.random.normal(size=4)

array([ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743])

In [172]:
# Random number from distribution with mean 15, variance 2
np.random.normal(15, 2)

15.137125949612054

In [257]:
# an array of 10 points randomly sampled from a normal distribution
# loc=mean, scale=std deviation
np.random.normal(loc=0.0, scale=1.0, size=10)

array([ 0.09707755,  0.96864499, -0.70205309, -0.32766215, -0.39210815,
       -1.46351495,  0.29612028,  0.26105527,  0.00511346, -0.23458713])

In [174]:
# To return a 8 by 5 array of random numbers from the same distribution: 
np.random.normal(15, 2, size=(3, 4))

array([[ 11.78503353,  15.36926772,  15.51976559,  16.56364574],
       [ 12.52609858,  12.35908677,  16.04388313,  15.59396935],
       [ 15.5009857 ,  15.69289642,  13.63995056,  15.46450739]])

In [176]:
# A 5 by 3 array of random numbers from the standard normal distribution 
# with mean 1 and variance 1:

np.random.normal(size=(2, 4))

array([[ 1.15859558, -0.82068232,  0.96337613,  0.41278093],
       [ 0.82206016,  1.89679298, -0.24538812, -0.75373616]])

In [177]:
# Generate Four Random Integers Between 1 and 100
np.random.randint(low=1, high=100, size=4)

array([22, 30, 38, 51])

In [178]:
# Randomly constructing 1D array
array = np.random.rand(5)
print("1D Array filled with random values : \n", array)

1D Array filled with random values : 
 [ 0.89204656  0.63113863  0.7948113   0.50263709  0.57690388]


In [182]:
# Randomly constructing 1D array following Gaussian Distribution

# 1D Array
array = np.random.normal(0.0, 1.0, 5)
print("1D Array filled with random values "
      "as per gaussian distribution : \n", array)

# 3D array
array = np.random.normal(0.0, 1.0, (2, 3))
print("\n\n2D Array filled with random values "
      "as per gaussian distribution : \n", array)

1D Array filled with random values as per gaussian distribution : 
 [-0.60390437  0.30444912  0.25720749  0.02393181  0.87191399]


3D Array filled with random values as per gaussian distribution : 
 [[ 1.43735633  0.00730637  1.33088133]
 [ 0.98820261  0.23229616  0.17618092]]


In [ ]:
# Making random numbers predictable *******************

In [183]:
# Set the state of the random number generator
np.random.seed(42)

In [184]:
# One set of random numbers
first_random_arr = np.random.normal(size=(2, 2))
print(first_random_arr)

# Another set
second_random_arr = np.random.normal(size=(2, 2))
print(second_random_arr)

# Reset the state of the random number generator
np.random.seed(42)

# The same as "first_random_arr" above.
print(np.random.normal(size=(2, 2)))

# The same as "second_random_arr" above.
print(np.random.normal(size=(2, 2)))

[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]]
[[-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]]
[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]]
[[-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]]


In [89]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

In [90]:
# Convert an array back to a list
arr1d_obj.tolist()

[1, 'a']

In [91]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]

arr2 = np.array(list2, dtype='float')
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [92]:
# Reverse only the row positions
arr2[::-1, ]

array([[ 5.,  6.,  7.,  8.],
       [ 3.,  4.,  5.,  6.],
       [ 1.,  2.,  3.,  4.]])

In [93]:
# Reverse the row and column positions
arr2[::-1, ::-1]

array([[ 8.,  7.,  6.,  5.],
       [ 6.,  5.,  4.,  3.],
       [ 4.,  3.,  2.,  1.]])

In [98]:
# represent missing values and infinite?
# Missing values can be represented using np.nan object, while np.inf represents infinite. 
# Let’s place some in arr2d.

# Insert a nan and an inf
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

array([[  1.,   2.,   3.,   4.],
       [  3.,  nan,  inf,   6.],
       [  5.,   6.,   7.,   8.]])

In [99]:
# Replace nan and inf with -1. 
missing_bool = np.isnan(arr2) | np.isinf(arr2)
print(missing_bool)

arr2[missing_bool] = -1  
arr2

[[False False False False]
 [False  True  True False]
 [False False False False]]


array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [100]:
# compute mean, min, max on the ndarray
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  3.58333333333
Max value is:  8.0
Min value is:  -1.0


In [102]:
# compute the minimum values row wise or column wise, use the np.amin 

# Row wise and column wise min
print("Column wise minimum : ", np.amin(arr2, axis=0))
print("Row wise minimum    : ", np.amin(arr2, axis=1))

Column wise minimum :  [ 1. -1. -1.  4.]
Row wise minimum    :  [ 1. -1.  5.]


In [ ]:
# Reshaping and Flattening Multidimensional arrays
# Reshaping is changing the arrangement of items so that shape of the array changes 
# while maintaining the same number of dimensions.

# Flattening, however, will convert a multi-dimensional array to a flat 1d array. 
# And not any other shape.

# First, let’s reshape the arr2 array from 3×4 to 4×3 shape.

In [107]:
# Reshape a 3x4 array to 4x3 array
arr2.reshape(4, 3)

array([[ 100.,    2.,    3.],
       [   4.,    3.,    4.],
       [   5.,    6.,    5.],
       [   6.,    7.,    8.]])

In [ ]:
# What is the difference between flatten() and ravel()?
# There are 2 popular ways to implement flattening. That is using the flatten() method 
# and the other using the ravel() method.

# The difference between ravel and flatten is, the new array created using ravel is 
# actually a reference to the parent array. 
# So, any changes to the new array will affect the parent as well. 
# But is memory efficient since it does not create a copy.

In [108]:
# Flatten it to a 1d array
arr2.flatten()

array([ 100.,    2.,    3.,    4.,    3.,    4.,    5.,    6.,    5.,
          6.,    7.,    8.])

In [111]:
# Changing the flattened array does not change parent
b1 = arr2.flatten()  
b1[0] = 105  # changing b1 does not affect arr2
arr2

array([[ 100.,    2.,    3.,    4.],
       [   3.,    4.,    5.,    6.],
       [   5.,    6.,    7.,    8.]])

In [112]:
b1

array([ 105.,    2.,    3.,    4.,    3.,    4.,    5.,    6.,    5.,
          6.,    7.,    8.])

In [113]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()  
b2[0] = 101  # changing b2 changes arr2 also
arr2


array([[ 101.,    2.,    3.,    4.],
       [   3.,    4.,    5.,    6.],
       [   5.,    6.,    7.,    8.]])

In [114]:
# create sequences, repetitions 
# Lower limit is 0 be default
print(np.arange(5))  

[0 1 2 3 4]


In [115]:
# 0 to 9
print(np.arange(0, 10))  

[0 1 2 3 4 5 6 7 8 9]


In [116]:
# 0 to 9 with step of 2
print(np.arange(0, 10, 2))  

[0 2 4 6 8]


In [117]:
# 10 to 1, decreasing order
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


In [119]:
# create repeating sequences?
# np.tile will repeat a whole list or array n times. 
# Whereas, np.repeat repeats each item n times.

a = [1,2,3] 

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 2 2 3 3]


In [ ]:
# Arrays support vectorised operations, while lists don’t.
# Once an array is created, you cannot change its size. You will have to create a new array 
# or overwrite the existing one.
# Every array has one and only one dtype. All items in it should be of that dtype.
# An equivalent numpy array occupies much less space than a python list of lists.

In [141]:
arr[4:7] = 15,16,17

In [142]:
arr

array([ 0.,  1.,  2.,  3., 15., 16., 17.,  7.,  8.,  9.], dtype=float32)

In [143]:
np.argmax(arr)

6

In [144]:
np.argmin(arr)

0