### An Array:
   - A **homogeneous container** of numerical elements. Each element in the array occupies a **fixed amount of memory** (hence homogeneous), and can be a numerical element of a **single type** (such as float, int or complex) or a **combination** (such as `(float, int, float))`. 
   - Each array has an associated data-type (or dtype), which describes the numerical type of its elements:

In [1]:
#Import Numpy library::
import numpy as np

### Diffeence between `np.int8`,`np.int16`,`np.int32`,`np.int64`:
[REFERENCE](https://numpy.org/doc/stable/user/basics.types.html)

|np.int8|np.int16 |np.int32 |np.int64 |
|:-------- |:-------- |:-------- |:-------|
|It takes single byte  space in the memory.|It takes 2-bytes  space in the memory. |It takes 4-bytes  space in the memory. |It takes 8-bytes  space in the memory. |
|The range of Int16 is from -128 to 127|The range of Int16 is from -32768 to +32767. |The range of Int32 is from -2147483648 to +2147483647. |The range of Int64 is from -9223372036854775808 to +9223372036854775807 |

#### Overflow Errors: When a value requires more memory than available in the data type it raise an `Overflow Error.`

In [2]:
np.power(100,8,dtype=int)

1874919424

In [3]:
np.power(12,2,dtype=np.int8)

-112

In [4]:
np.power(12,2,dtype=np.int16)

144

In [5]:
np.power(100, 8, dtype=np.int32)

1874919424

In [6]:
np.power(100, 8, dtype=np.int64)

10000000000000000

#### NumPy provides `numpy.iinfo` and `numpy.finfo` to verify the minimum or maximum values of NumPy integer and floating point values respectively:

In [7]:
# Bounds of the default integer on this system.
np.iinfo(np.int) 

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [8]:
# Bounds of a 8-bit integer
np.iinfo(np.int8) 

iinfo(min=-128, max=127, dtype=int8)

In [9]:
# Bounds of a 16-bit integer
np.iinfo(np.int16) 

iinfo(min=-32768, max=32767, dtype=int16)

In [10]:
# Bounds of a 32-bit integer
np.iinfo(np.int32) 

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [11]:
# Bounds of a 64-bit integer
np.iinfo(np.int64) 

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

#### If 64-bit integers are still too small the result may be cast to a floating point number. Floating point numbers offer a larger, but inexact, range of possible values:

In [12]:
np.power(100, 100, dtype=np.int64) # Incorrect even with 64-bit int

0

In [13]:
100**100

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [14]:
np.power(100, 100, dtype=np.float64)

1e+200

In [15]:
1*(10**200)

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

### Get index locations that satisfy a given condition using np.where:

### `1D`:

In [3]:
arr_rand = np.array([8, 8, 3, 7, 7, 1, 4, 2, 5, 2, 0])
print("Array: ", arr_rand)

Array:  [8 8 3 7 7 1 4 2 5 2 0]


In [7]:
index_less_5 = np.where(arr_rand > 5)
index_less_5

(array([0, 1, 3, 4], dtype=int64),)

In [8]:
arr_rand[index_less_5]

array([8, 8, 7, 7])

### `2D:`

In [5]:
arr_rand_2d = np.random.randint(0,10,size=(3,3))
arr_rand_2d

array([[4, 9, 2],
       [3, 1, 1],
       [9, 6, 7]])

#### When only `condition` is provided, this function is a shorthand for ``np.asarray(condition).nonzero()``:

**`nonzero()`**:Return the indices of the elements that are non-zero.

In [10]:
arr_rand_2d.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [11]:
arr_rand_2d

array([[4, 9, 2],
       [3, 1, 1],
       [9, 6, 7]])

In [9]:
np.asarray(arr_rand_2d > 5).nonzero()

(array([0, 2, 2, 2], dtype=int64), array([1, 0, 1, 2], dtype=int64))

In [15]:
arr_rand_2d

array([[4, 9, 2],
       [3, 1, 1],
       [9, 6, 7]])

In [16]:
index_grt_5 = np.where(arr_rand_2d > 5)
index_grt_5

(array([0, 2, 2, 2], dtype=int64), array([1, 0, 1, 2], dtype=int64))

In [17]:
type(index_grt_5) #Tuple of arrays

tuple

In [18]:
len(index_grt_5)

2

In [20]:
index_grt_5[1]

array([1, 0, 1, 2], dtype=int64)

In [13]:
extracted_elements = arr_rand_2d.take(index_less_5)
extracted_elements

array([[4, 2, 2, 2],
       [9, 4, 9, 2]])

In [39]:
arr_rand_2d.take((0,1))

array([4, 9])

In [22]:
arr_rand_2d.take((2,0))

array([2, 4])

In [26]:
arr_rand_2d.take((2,1))

array([2, 9])

In [27]:
arr_rand_2d.take((2,2))

array([2, 2])

In [29]:
arr_rand_2d[index_grt_5]

array([9, 9, 6, 7])

In [34]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
arr < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [36]:
np.where(arr<5)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [37]:
arr[np.where(arr<5)]

array([0, 1, 2, 3, 4])

In [25]:
#The same thing is achieved through---
#Positions where value < 5
#[xv if c else yv
#     for c, xv, yv in zip(condition, x, y)]
index_less5 = np.where(arr_rand < 5)
print("Positions where value > 5: ", index_less5)

Positions where value > 5:  (array([ 2,  5,  6,  7,  9, 10], dtype=int64),)


In [26]:
type(index_less5)

tuple

In [27]:
len(index_less5)

1

In [28]:
#Extract them using the array’s take method:
#Return an array formed from the elements of `a` at the given indices.
returned_arr = arr_rand.take(index_less5)
returned_arr

array([[3, 1, 4, 2, 2, 0]])

In [29]:
#Check shape & Dimention:
returned_arr.shape,returned_arr.ndim

((1, 6), 2)

In [30]:
arr_rand

array([8, 8, 3, 7, 7, 1, 4, 2, 5, 2, 0])

### Value assignment based on condition satisfied:

In [31]:
# If value > 5, then yield 'gt5' else 'le5'
np.where(arr_rand > 5, 'gt5', 'le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5', 'le5'], dtype='<U3')

### Import and Export data as a csv file:

- **`np.genfromtxt` function:** It imports datasets from web URLs,handle missing values,multiple delimiters and handle irregular number of columns etc.

In [32]:
# Import data from csv file url
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'

In [33]:
org_data.isna().sum()

NameError: name 'org_data' is not defined

In [ ]:
import pandas as pd
org_data = pd.read_csv(path)
org_data.head(7)

In [ ]:
#Import data using Numpy:
data = np.genfromtxt(path, delimiter=',', skip_header=1,missing_values=np.nan,filling_values=-999, dtype='float')
data

In [ ]:
org_data.shape

In [ ]:
data.shape

In [ ]:
#Check attributes:
data.shape,data.ndim

In [ ]:
# View first 3 rows fully:
data[:3]

In [ ]:
#Turn off scientific notation
np.set_printoptions(suppress=True)  

In [ ]:
data[:5]

- Notice all the values in last column has the same value `‘-999’?`

- **Cause:**
    - That happened because, `dtype=’float’`. 
    - The last column in the file contained text values and since all the values in a numpy array has to be of the same `dtype`, `np.genfromtxt` didn’t know how to convert it to a float.

### Handle datasets that has both numbers and text columns?
- set the dtype as `‘object’` or as `None`

In [ ]:
data_2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype='object')
data_2

In [ ]:
data_2

In [ ]:
data_2[:3]

In [ ]:
data_3 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)
data_3[:5]

In [ ]:
# Save the array as a csv file
np.savetxt("out.csv", data, delimiter=",")

### Array Concatenation:
   - Concatenate two numpy arrays columnwise and row wise.
   - There are 2 different ways of concatenating two or more numpy arrays and these are:
       - **`np.concatenate`** by changing the axis parameter to 0 and 1
       
       - **`np.vstack`** and **`np.hstack`**

In [ ]:
a = np.zeros([4, 4])
b = np.ones([4, 4])
print("a--\n",a)
print()
print("b--\n",b)

In [ ]:
#========Stack the arrays vertically(Increatment in Rows in the Resultant Array)========#.
#Vertical Stack Equivalents(Row wise)::Using "np.concatenate(axis=0)" method.
np.concatenate((a, b), axis=0)  

In [ ]:
#Using "np.vstack" method::
np.vstack([a,b])  

In [ ]:
#========Stack the arrays Horizontally(Increatment in Columns in the Resultant Array)========#.
#Horizontal Stack Equivalents(Column wise)::Using "np.concatenate(axis=1)" method.
np.concatenate([a, b], axis=1) 

In [ ]:
#Using "np.hstack" method::
np.hstack([a,b])  

---
***

### Getting every Yth element from an array:

In [156]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`array[start:end:step_size]`

In [159]:
#Example-1:
#Providing Start Index but not end Index:
arr[2::2]

array([3, 5, 7, 9])

In [160]:
#Example-2:
#Providing End Index but not Start Index:
arr[:6:2]

array([1, 3, 5])

In [161]:
#Example-3:
#Providing both Start & End Indexes:
arr[1:8:2]

array([2, 4, 6, 8])

In [84]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### `array[end:start:-1]`:

In [164]:
#Some experimentations with list:
test_list = list(range(20))
test_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [166]:
#Reverse entire list:
#test_list[::-1]

In [92]:
test_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [165]:
#Example-1::
test_list[12:7:-1]

[12, 11, 10, 9, 8]

In [167]:
#Example-2::
test_list[10:4:-1]

[10, 9, 8, 7, 6, 5]

In [168]:
#Example-3::<<Step-size of 2>>
test_list[10:4:-2]

[10, 8, 6]

In [91]:
#Same working with arrays:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
#Reverses::
#getting entire array in reverse order:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [86]:
arr[::-2]

array([9, 7, 5, 3, 1])

In [43]:
arr[::-3]

array([9, 6, 3])

In [169]:
arr_2d = np.random.randint(10,20,size=(4,4))
arr_2d

array([[16, 12, 10, 18],
       [12, 15, 11, 18],
       [11, 15, 14, 12],
       [18, 13, 15, 10]])

In [172]:
arr_2d[1:3,2:]

array([[11, 18],
       [14, 12]])

### Sorting values based on the given axis::
   - `np.sort` function with `axis=0`:
        - All the columns will be sorted in ascending order independent of each-other.
        
### Using `np.sort()`:Direct Sorting

### Sorting:

   1. **Direct**
       - In place sorting
       - Return array copy
   
   
   2. **Indirect**
      - In place sorting
      - Return array copy

### `1D:`

In [176]:
arr_1d = np.random.randint(10,size=10)
arr_1d

array([4, 4, 5, 7, 6, 6, 2, 4, 2, 7])

In [174]:
#Perform sorting:
#In-Place sorting:
arr_1d.sort()

In [175]:
#By default in ascending order: 
arr_1d

array([0, 3, 3, 3, 4, 6, 6, 7, 9, 9])

In [177]:
arr_1d

array([4, 4, 5, 7, 6, 6, 2, 4, 2, 7])

In [178]:
np.sort(arr_1d)

array([2, 2, 4, 4, 4, 5, 6, 6, 7, 7])

In [179]:
arr_1d

array([4, 4, 5, 7, 6, 6, 2, 4, 2, 7])

In [97]:
#To make it in descending order:
#array[::-1].sort() sorts the array in place, whereas np.sort(array)[::-1] creates a new array:
np.sort(arr_1d)[::-1]

array([9, 8, 5, 5, 5, 5, 4, 4, 3, 2])

### along an axis:
   Axes are defined for arrays with **more than one dimension**. A 2-dimensional array has **two corresponding axes:** 
   - the **first** running **vertically downwards** across rows (**axis 0**), 
   - and the **second** running **horizontally** across columns (**axis 1**).

Many operation can take place along one of these axes. For example, we can sum each row of an array, in which case we operate along columns, or axis 1:
```
>>> x = np.arange(12).reshape((3,4))

>>> x
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

>>> x.sum(axis=1)
array([ 6, 22, 38])
```

In [75]:
#Row-wise:
np.sort(arr, axis=0)

array([[1, 1, 1, 3],
       [2, 3, 1, 3],
       [3, 3, 3, 4],
       [3, 3, 3, 4],
       [3, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 5, 4, 5],
       [5, 5, 5, 5]])

In [180]:
# sort a numpy array based on one or more columns?
arr = np.random.randint(1,6,size=(8, 4))
arr

array([[5, 2, 3, 3],
       [1, 3, 3, 4],
       [5, 3, 5, 4],
       [2, 1, 1, 2],
       [3, 5, 3, 4],
       [4, 2, 3, 4],
       [1, 2, 2, 4],
       [1, 5, 3, 5]])

In [181]:
#Column-wise:
np.sort(arr, axis=1)

array([[2, 3, 3, 5],
       [1, 3, 3, 4],
       [3, 4, 5, 5],
       [1, 1, 2, 2],
       [3, 3, 4, 5],
       [2, 3, 4, 4],
       [1, 2, 2, 4],
       [1, 3, 5, 5]])

### `np.argsort`: Indirect Sorting
- `np.argsort` returns the **index positions** of that would make a given array sorted.

### `1D`:

In [183]:
x = np.array([1, 10, 5, 2, 8, 9])
x

array([ 1, 10,  5,  2,  8,  9])

In [184]:
# Get the index positions that would sort the array
sort_index = np.argsort(x)
print(type(sort_index))

<class 'numpy.ndarray'>


In [185]:
print(sort_index)

[0 3 2 4 5 1]


- In array `‘x’`, the `0th item` is the `smallest`, `3rd item` is the `second smallest` and so on.

In [187]:
#Sort the array:
x[sort_index][::-1]

array([10,  9,  8,  5,  2,  1])

### `2D:`

In [188]:
x_2d = np.random.randint(10,size=(3,3))
x_2d

array([[3, 4, 8],
       [9, 8, 5],
       [2, 7, 5]])

In [193]:
#Column-major:
x_2d.flatten(order='F')

array([3, 9, 2, 4, 8, 7, 8, 5, 5])

In [194]:
x_2d

array([[3, 4, 8],
       [9, 8, 5],
       [2, 7, 5]])

In [191]:
#Flattend version of 2D array:
#Rows-wise:
x_2d.flatten()

array([3, 4, 8, 9, 8, 5, 2, 7, 5])

In [195]:
#Flattend before sort:
sort_index_2d = np.argsort(x_2d,axis=None)
sort_index_2d

array([6, 0, 1, 5, 8, 7, 2, 4, 3], dtype=int64)

In [202]:
#By default:Sorted along with last axis which is 'column':
sort_index_2d = np.argsort(x_2d)
sort_index_2d

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]], dtype=int64)

In [201]:
x_2d

array([[3, 4, 8],
       [9, 8, 5],
       [2, 7, 5]])

In [203]:
#Sorts along with rows:
sort_index_2d = np.argsort(x_2d,axis=0)
sort_index_2d

array([[2, 0, 1],
       [0, 2, 2],
       [1, 1, 0]], dtype=int64)

In [212]:
#Original array:
x_2d

array([[3, 4, 8],
       [9, 8, 5],
       [2, 7, 5]])

In [213]:
#Sorts along with column:
sort_index_2d = np.argsort(x_2d,axis=1)
sort_index_2d

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]], dtype=int64)

In [211]:
#Sort the array:
x_2d[sort_index_2d]

array([[[3, 4, 8],
        [9, 8, 5],
        [2, 7, 5]],

       [[2, 7, 5],
        [9, 8, 5],
        [3, 4, 8]],

       [[3, 4, 8],
        [2, 7, 5],
        [9, 8, 5]]])

#### Use the `order` keyword to specify a field to use when sorting a structured array:

In [216]:
#===========[1]===========#
#Specifiy data-types of the values::
d_type = [('name', 'S10'), ('height', np.float), ('age', np.int8),('Rank',np.float)]
#===========[2]===========#
#Values for the array:
values = [('Tejas', 5.8, 29,1), ('Satish', 5.3, 39,1),('Vinayak',5.9, 41, 1.2),('Sunil',5.4, 42, 1.3)]
#===========[3]===========#
#Create an array::
a = np.array(values, dtype=d_type)
#===========[4]===========#
#Sorting based on criteria:
np.sort(a, order='height')[::-1]

array([(b'Vinayak', 5.9, 41, 1.2), (b'Tejas', 5.8, 29, 1. ),
       (b'Sunil', 5.4, 42, 1.3), (b'Satish', 5.3, 39, 1. )],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', 'i1'), ('Rank', '<f8')])

In [218]:
#Sort by 'Rank', then 'height' if Ranks are equal:
np.sort(a,order=['Rank','height'])[::-1]

array([(b'Sunil', 5.4, 42, 1.3), (b'Vinayak', 5.9, 41, 1.2),
       (b'Tejas', 5.8, 29, 1. ), (b'Satish', 5.3, 39, 1. )],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', 'i1'), ('Rank', '<f8')])

In [219]:
#Check attributes:
a.shape,a.ndim

((4,), 1)

### Working with `Dates`::
   - Numpy implements dates through the `np.datetime64` object which supports a precision till nanoseconds. 
   - You can create one using a standard `YYYY-MM-DD` formatted date strings.

In [220]:
#Get current date and time:
np.datetime64('today')

numpy.datetime64('2020-08-19')

In [221]:
np.datetime64('now')

numpy.datetime64('2020-08-19T10:21:38')

In [222]:
# Create a datetime64 object
date64 = np.datetime64(np.datetime64('now'))
date64

numpy.datetime64('2020-08-19T10:23:03')

In [223]:
# Drop the time part from the datetime64 object and get only 'Year' part::
dt64 = np.datetime64(date64, 'Y')
dt64

numpy.datetime64('2020')

In [224]:
# Drop the time part from the datetime64 object and get only 'Month' part::
dt64 = np.datetime64(date64, 'M')
dt64

numpy.datetime64('2020-08')

In [230]:
# Drop the time part from the datetime64 object and get only 'Day' part::
dt64 = np.datetime64(date64, 'D')
dt64

numpy.datetime64('2020-08-19')

### Create a sequence of dates::

In [226]:
dates = np.arange(np.datetime64('2020-05-01'), np.datetime64('2020-05-11'))
print(dates)

['2020-05-01' '2020-05-02' '2020-05-03' '2020-05-04' '2020-05-05'
 '2020-05-06' '2020-05-07' '2020-05-08' '2020-05-09' '2020-05-10']


In [227]:
dates = np.arange(np.datetime64('2020-05-01'), np.datetime64('2020-05-11'),2)
print(dates)

['2020-05-01' '2020-05-03' '2020-05-05' '2020-05-07' '2020-05-09']


In [228]:
#All the dates for one month:
np.arange('2020-07', '2020-08', dtype='datetime64[D]')

array(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
       '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
       '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
       '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
       '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
       '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
       '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
       '2020-07-29', '2020-07-30', '2020-07-31'], dtype='datetime64[D]')

In [231]:
dt64

numpy.datetime64('2020-08-19')

In [238]:
# Create the timedeltas (individual units of time)
tenminutes = np.timedelta64(10, 'm')  # 10 minutes
tenseconds = np.timedelta64(10, 's')  # 10 seconds
milliseconds = np.timedelta64(10, 'ms')  # 10 nanoseconds

print('Add 10 days: ', dt64 + 10)

Add 10 days:  2020-08-29


In [233]:
print('Add 10 minutes: ', dt64 + tenminutes)

Add 10 minutes:  2020-08-19T00:10


In [234]:
print('Add 10 seconds: ', dt64 + tenseconds)

Add 10 seconds:  2020-08-19T00:00:10


In [239]:
print('Add 10 nanoseconds: ', dt64 + milliseconds)

Add 10 nanoseconds:  2020-08-19T00:00:00.010


### `np.is_busday():`

In [240]:
np.is_busday(np.datetime64(np.datetime64('today'))) #Today is Wednesday(working-day)

True

In [241]:
#let's check for 'Saturday'::
np.is_busday(np.datetime64('2020-08-22'))

False

In [242]:
week = np.arange(np.datetime64('2020-08-24'), np.datetime64('2020-08-31'))
np.is_busday(week)

array([ True,  True,  True,  True,  True, False, False])

### `np.busday_count():`

In [143]:
np.busday_count(np.datetime64('2020-08-24'), np.datetime64('2020-08-31'))

5

In [147]:
a = np.arange(np.datetime64('2020-08-24'), np.datetime64('2020-08-31'))
a

array(['2020-08-24', '2020-08-25', '2020-08-26', '2020-08-27',
       '2020-08-28', '2020-08-29', '2020-08-30'], dtype='datetime64[D]')

In [148]:
np.count_nonzero(np.is_busday(a))

5

### Application of `functions` on `Column` or `Row`:

```
>>>x = np.datetime64('2010-06-01T00:00:00.000000000')
>>>x = pd.to_datetime(x)

>>>str(x.date())
>>>'2010-06-01'
```
or
```
>>>x = []
>>>for i in ['2010-06-01T00:00:00.000000000', '2010-12-02T00:00:00.000000000']:

>>>    x.append(np.datetime64(i)) 

>>>date_df = pd.to_datetime(x)

>>>[str(i.date()) for i in x]

>>>Output::['2010-06-01', '2010-12-02']
```

#### Define a scalar function::

In [1]:
#Function definition:
def test(x):
    #If-Else:
    if x % 2 == 1:
        return x**2
    else:
        return x/2

In [2]:
# On a scalar
print('x = 10 returns ', test(10))
print('x = 11 returns ', test(11))

x = 10 returns  5.0
x = 11 returns  121


#### Apply along axis::
   - Row-wise or 
   - Column-wise

In [4]:
import numpy as np

In [6]:
# Create a 4x10 random array
np.random.seed(100)
arr_x = np.random.randint(1,10,size=(4,10))
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

### **Task::** Find the difference of the maximum and the minimum value in each row?
 - The normal approach would be to write a for-loop that iterates along each row and then compute the max-min in each iteration.
 >___That sounds alright but it can get cumbersome if you want to do the same column wise___.
 - As a solution on this using the `numpy.apply_along_axis` function.
 ***
 - `numpy.apply_along_axis` takes:
     - **Function** that works on a 1D vector.
     - **Axis** along which to apply func1d. 
         - For a 2D array:
             - **0** is `row wise` and 
             - **1** is `column wise`.
     - **Array** on which function 1D should be applied.
***
***

>_We can sum each row of an array, in which case we operate_ **_along columns, or axis 1._**

And

>_We can sum each column of an array, in which case we operate_ **_across rows, or axis 0._**

- Let's perform experiment:

In [9]:
# Define func1d
def max_minus_min(x):
    return np.max(x) - np.min(x)

In [10]:
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [11]:
# Finding difference between Max and Min value in each column(in this case we operate across rows)::
# And that's why we mention "axis = 0"(Vertically downwards)
print('Column operation: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Row wise:  [7 8 2 7 6 5 8 5 5 5]


In [12]:
# Finding difference between Max and Min value in each row(in this case we operate along columns)::
# And that's why we mention "axis = 1"(Horizontally moving)
print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

Row wise:  [8 8 6 8]


### This is all about numpy..........!
### .

### .


## What is missing in numpy?
- So far we have covered a good number of techniques to do data manipulations with numpy. But there are a considerable number of things you can’t do with numpy directly which are::
    - No direct function to merge two 2D arrays based on a common column.
    - Create pivot tables directly
    - No direct way of doing 2D cross tabulations.
    - No direct method to compute statistics (like mean) grouped by unique values in an array.
    - And more..

## To Answer all of this -- `pandas` data-structure